### ISSUE TITLE
truncation error for 32-bit integer coding

### ISSUE THREAD

**Issue by parithon** [lextm/sharpsnmplib#30]
I keep getting the following error 80% of the time while calling: Messenger.Get

Lextm.SharpSnmpLib.SnmpException: data construction exception ---> System.ArgumentException: truncation error for 32-bit integer coding
Parameter name: length
   at Lextm.SharpSnmpLib.Integer32..ctor(Tuple`2 length, Stream stream)
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Int32 type, Stream stream)
   --- End of inner exception stack trace ---
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Int32 type, Stream stream)
   at Lextm.SharpSnmpLib.ResponsePdu..ctor(Tuple`2 length, Stream stream)
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Int32 type, Stream stream)
   at Lextm.SharpSnmpLib.Sequence..ctor(Tuple`2 length, Stream stream)
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Int32 type, Stream stream)
   at Lextm.SharpSnmpLib.Messaging.MessageFactory.ParseMessage(Int32 first, Stream stream, UserRegistry registry)
   at Lextm.SharpSnmpLib.Messaging.MessageFactory.ParseMessages(Byte[] buffer, Int32 index, Int32 length, UserRegistry registry)
   at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver, UserRegistry registry, Socket udpSocket)
   at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver, Socket udpSocket)
   at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver)
   at Lextm.SharpSnmpLib.Messaging.Messenger.Get(VersionCode version, IPEndPoint endpoint, OctetString community, IList`1 variables, Int32 timeout)
   at EnvConf.Program.<GetSnmpInfo>d__1.MoveNext() in ...\Program.cs:line 48

```
const string endpointInput = "192.168.1.1";
            const string communityInput = "public";

            if (!IPAddress.TryParse(endpointInput, out IPAddress ip))
            {
                foreach ( var address in (await Dns.GetHostAddressesAsync(endpointInput))
                        .Where(address => address.AddressFamily == AddressFamily.InterNetwork))
                {
                    ip = address;
                    break;
                }
                if (ip == null)
                {
                    Console.WriteLine("IP Address was not valid.");
                    return;
                }
            }

            try
            {
                var vList = new List<Variable>()
                {
                    new Variable(new ObjectIdentifier("1.3.6.1.2.1.1.5.0")),
                    new Variable(new ObjectIdentifier("1.3.6.1.2.1.1.1.0"))
                };

                var endpoint = new IPEndPoint(ip, 161);
                foreach (var variable in Messenger.Get(VersionCode.V2, endpoint, new OctetString(communityInput), vList, 1000))
                {
                    Console.WriteLine($"{variable.Id}: {variable.Data}");
                }
            }
            catch (SnmpException ex)
            {
                Console.WriteLine(ex);
            }
            catch (SocketException ex)
            {
                Console.WriteLine(ex);
            }
```

I'm using Visual Studio 2017 RTM with .Net Core.

**Comment by lextm** [comment]
Are you using the latest 9.0.x releases in a .NET Core app? I personally also see similar issues, and they seem to be .NET Core only.

**Comment by parithon** [comment]
Yes, I am using a .NET Core console app (.netcoreapp 1.1) with the 1.0 SDK released with Visual Studio 2017.

**Comment by lextm** [comment]
Thanks. That's kind of expected, before I could spare some time to dig further into this issue. Will provide an update once some progress is there.

**Comment by lextm** [comment]
As #71 revealed, the error might be related to the target SNMP device which does not support negative request ID numbers.

As a workaround, the master branch now adds a new `Messenger.UseFullRange` property. By default, it would be `true` which indicates request ID numbers go the full range.

If your target device does fail to process negative request ID numbers, you can set this property to `false` and see if it avoids the error.

The changes should be part of 10.0.5 release, which should be out soon.
