### ISSUE TITLE
SNMPv2 BulkWalk causes "unsupported data type: 18" exception

### ISSUE THREAD

**Issue by nickaein** [lextm/sharpsnmplib#89]
The remote SNMP agent is a Microtik RouterOS.  

Calling `BulkWalk` of SNMPv2:

```
Messenger.BulkWalk(VersionCode.V2, RemoteDeviceAddress, new OctetString("public"), 
   new OctetString(""), new ObjectIdentifier("1.3"),resultOids, 3000, 10, 
   WalkMode.WithinSubtree, null, null);
```

fails with the following exception:

```
Lextm.SharpSnmpLib.SnmpException: unsupported data type: 18
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Int32 type, Stream stream)
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Stream stream)
   at Lextm.SharpSnmpLib.Sequence..ctor(Tuple`2 length, Stream stream)
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Int32 type, Stream stream)
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Stream stream)
   at Lextm.SharpSnmpLib.ResponsePdu..ctor(Tuple`2 length, Stream stream)
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Int32 type, Stream stream)
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Stream stream)
   at Lextm.SharpSnmpLib.Sequence..ctor(Tuple`2 length, Stream stream)
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Int32 type, Stream stream)
   at Lextm.SharpSnmpLib.Messaging.MessageFactory.ParseMessage(Int32 first, Stream stream, UserRegistry registry)
   at Lextm.SharpSnmpLib.Messaging.MessageFactory.ParseMessages(Byte[] buffer, Int32 index, Int32 length, UserRegistry registry)
   at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver, UserRegistry registry, Socket udpSocket)
   at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver, Socket udpSocket)
   at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver)
   at Lextm.SharpSnmpLib.Messaging.Messenger.BulkHasNext(VersionCode version, IPEndPoint receiver, OctetString community, OctetString contextName, Variable seed, Int32 timeout, Int32 maxRepetitions, IList`1& next, IPrivacyProvider privacy, ISnmpMessage& report)
   at Lextm.SharpSnmpLib.Messaging.Messenger.BulkWalk(VersionCode version, IPEndPoint endpoint, OctetString community, OctetString contextName, ObjectIdentifier table, IList`1 list, Int32 timeout, Int32 maxRepetitions, WalkMode mode, IPrivacyProvider privacy, ISnmpMessage report)
   at SNMPTester.SNMPClient.Walk(String oid) in C:\Users\nickaein\Desktop\git\snmp-tester\SNMP Tester\SNMPClient.cs:line 186
   at SNMPTester.Form1.button1_Click(Object sender, EventArgs e) in C:\Users\nickaein\Desktop\git\snmp-tester\SNMP Tester\Form1.cs:line 69
```

However, calling `Walk` with SNMPv1 works without any issue:

```
Messenger.Walk(VersionCode.V1, RemoteDeviceAddress, new OctetString("public"),
   new ObjectIdentifier("1.3"), resultOids, 3000, WalkMode.WithinSubtree);
```

**Comment by nickaein** [comment]
There seems to be an issue in the response packet:

![image](https://user-images.githubusercontent.com/8047027/45098646-a6d50d00-b13a-11e8-9698-c53b783013e0.png)

Here is the full Wireshark capture log: https://file.io/q1D2I2

It seems that I might be a bug in the SNMP agent, right? I expected more from a well-known company like Mikrotik.

**Comment by lextm** [comment]
Right. Some devices might contain legacy code (written before SNMP v2c is fully standardized).

I did a quick check, but could not see what legacy data type 18 maps to.

You might have to check if the vendor has an update for this device. Usually only the vendor has a way to address it.
